<a href="https://colab.research.google.com/github/jin-wook-lee-96/stydy/blob/main/ai_mathematics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print('hello world')

hello world


In [2]:
import numpy as np


In [ ]:
v = np.array([0.61,0.93,0.24,0.27])
v

array([0.61, 0.93, 0.24, 0.27])

In [ ]:
v[0]

0.61

In [ ]:
v.shape

(4,)

In [ ]:
v_sub = v[0:2]
v_sub

array([0.61, 0.93])

In [ ]:
size = 3
zeros = np.zeros(shape=(size,))
zeros

array([0., 0., 0.])

In [ ]:
size = 3
one = np.ones(shape = (size,))
one

array([1., 1., 1.])

In [ ]:
size = 3
e = np.zeros(shape = (3,))
i = 1
e[i] = 1
e

array([0., 1., 0.])

In [ ]:
a = np.array([1,3])
b = np.array([3,1])
a + b

array([4, 4])

In [ ]:
a = np.array([1,3])
b = np.array([3,1])
a + b

array([4, 4])

In [ ]:
a + b == b + a

array([ True,  True])

In [ ]:
d = np.array([1,2])
(a + b) + d == a + (b+ d)

array([ True,  True])

안ㄴ능ㄹㄴ룽나루ㅏ루ㅏㅜㄹ